import './globals.css'
import {Footer} from "@/component/Footer/Footer";
import {Header} from "@/component/Header/Header";
import {ReduxProvider} from "@/state/provider";
import React, {ReactNode} from "react";
import {HeaderProvider} from "@/component/Header/HeaderProvider/HeaderProvider";
import {MobileMenu} from "@/component/Header/MobileMenu/MobileMenu";
import MobileMenuRefactor from "@/component/Header/MobileMenuRefactor/MobileMenuRefactor";

export const metadata = {
    title: 'Main Leyout',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <ReduxProvider>
            <HeaderProvider>
                {/*<Header/>*/}
                <MobileMenuRefactor />
            </HeaderProvider>
            <main>
                {children}
            </main>
            <Footer/>
        </ReduxProvider>
        </body>
        </html>
    )
}
