import './globals.css'
import {Footer} from "@/component/Footer/Footer";
import {Header} from "@/component/Header/Header";

export const metadata = {
    title: 'Main Leyout',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <Header/>
        <main>
            {children}
        </main>
        <Footer/>
        </body>
        </html>
    )
}
