import './globals.css'
import {Footer} from "@/component/Footer/Footer";
import {Header} from "@/component/Header/Header";
import Reviews from '@/component/Reviews/Reviews';
import {ReduxProvider} from "@/state/provider";
import {ReactNode} from "react";

export const metadata = {
    title: 'Main Leyout',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <ReduxProvider>
            <Header/>
            <main>
                {children}
            </main>
            <Reviews /> 
            <Footer/>

                    
        </ReduxProvider>
        </body>
        </html>
    )
}
