import '../globals.css'
import {Footer} from "@/component/Footer/Footer";
import {Header} from "@/component/Header/Header";
import {ReduxProvider} from "@/state/provider";
import React, {ReactNode} from "react";
import {headers} from "next/headers";
import {NextIntlClientProvider, useMessages} from 'next-intl';
import {unstable_setRequestLocale} from "next-intl/server";
import {locales} from "../../../i18n/config";

export const metadata = {
    title: 'Main Leyout',
    description: 'Generated by create next app',
}

export function generateStaticParams() {
    return locales.map((locale) => ({locale}));
}

export default function RootLayout({
                                       children,
                                       params: {locale}
                                   }: {
    children: ReactNode,
    params: { locale: string },
}) {
    const messages = useMessages();
    unstable_setRequestLocale(locale);

    return (
        <html lang={locale}>
        <body>
        <ReduxProvider>
            <NextIntlClientProvider messages={messages}>
                <Header locale={locale}/>
                <main>
                    {children}
                </main>
                <Footer/>
            </NextIntlClientProvider>
        </ReduxProvider>
        </body>
        </html>
    )
}
